ailingx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from ailingx.core import views as core_views
from demo import views,urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),

    url(r'^home/$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),

    url(r'^usecase/$', core_views.usecase, name='usecase'),
    url(r'^feature/$', core_views.feature, name='feature'),
    url(r'^blog/$', core_views.blog, name='blog'),
    url(r'^team/$', core_views.team, name='team'),
    url(r'^joinus/$', core_views.joinus, name='joinus'),
    url(r'^contact/$', core_views.contact, name='contact'),

    url(r'^admin/', admin.site.urls),

    url(r'^demo/', include('demo.urls', namespace='demo')),
    url(r'^tenihe/', include('tenihe.urls', namespace='tenihe')),

] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

demo/urls.py
from django.conf.urls import url
from demo import views

urlpatterns = [
    url(r'^demogis/$', views.demogis, name='demogis'),
    url(r'^demomap/(\d+)$', views.demomap, name='demomap'),
]

tenihe/urls.py
from django.conf.urls import url
from tenihe import views

urlpatterns = [
    url(r'^tenihegis/$', views.tenihegis, name='tenihegis'),
    url(r'^tenihemap/(\d+)$', views.tenihemap, name='tenihemap'),
]

ailingx/core/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Area(models.Model):
    name = models.CharField('Area name', max_length=30)
    location = models.CharField('Area location', max_length=60)
    info = models.TextField('Area Information', max_length=500)
    sqkm = models.IntegerField('Area Square meter')

    def __unicode__(self):
        return self.name


class Block(models.Model):
    area = models.ForeignKey(Area)
    name = models.CharField('Block name', max_length=30)
    location = models.CharField('Block location', max_length=60)
    info = models.TextField('Block Information', max_length=500)
    sqkm = models.IntegerField('Block Square meter')

    def __unicode__(self):
        return self.name


class Cell(models.Model):
    block = models.ForeignKey(Block)
    user = models.ManyToManyField(User)
    name = models.CharField('Cell name', max_length=30)
    location = models.CharField('Cell location', max_length=60)
    info = models.TextField('Cell Information', max_length=500)
    sqm = models.IntegerField('Cell Square meter')
    user = models.ManyToManyField(User)

    def __unicode__(self):
        return self.name

ailingx/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username', 'birth_date', 'password1', 'password2', )

ailingx/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from ailingx.core.forms import SignUpForm
from ailingx.core.models import Area



@login_required
def home(request):
    curuser = request.user
    cells = curuser.cell_set.all()
    return render(request, 'home.html', {'curuser': curuser, 'cells': cells})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def index(request):
    return render(request, 'index.html')


def usecase(request):
    areas = Area.objects.all()
    return render(request, 'usecase.html', {'areas': areas})


def feature(request):
    return render(request, 'feature.html')


def blog(request):
    return render(request, 'blog.html')


def team(request):
    return render(request, 'team.html')


def joinus(request):
    return render(request, 'joinus.html')


def contact(request):
    return render(request, 'contact.html')

ailingx/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}-{% endblock %}</title>
        {% load static %}

        <link rel="stylesheet" href="{% static 'css/indexstyle.css' %}" type="text/css" media="all">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" media="all">
        <link rel="stylesheet" href="{% static 'css/core.css' %}" type="text/css" media="all">

        <script src="{%  static 'js/demo.js' %}"></script>
        <script src="{%  static 'js/jquery.particleground.js' %}"></script>
        <script src="{%  static 'js/jquery-1.11.1.min.js' %}"></script>
        <script src="{%  static 'js/bootstrap.js' %}"></script>
        <script src="{%  static 'js/npm.js' %}"></script>


    </head>
    <body>
        <header id="baseheader">
            <div class="container" id="header">
                <div class="row clearfix">
                    <div class="col-md-12 column">
                        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
                            <div class="navbar-header">
                                 <button type="button" class="navbar-toggle" data-toggle="collapse"
                                         data-target="#bs-example-navbar-collapse-1">
                                     <span class="sr-only">Toggle navigation</span>
                                     <span class="icon-bar"></span>
                                     <span class="icon-bar"></span>
                                     <span class="icon-bar"></span>
                                 </button> <a class="navbar-brand" href="{% url 'index' %}">Ailingx</a>
                            </div>

                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="active">
                                         <a href="{% url 'feature' %}">特性</a>
                                    </li>
                                    <li>
                                         <a href="{% url 'usecase' %}">案例</a>
                                    </li>
                                    <li class="dropdown">
                                         <a href="#" class="dropdown-toggle" data-toggle="dropdown">关于我们<strong class="caret"></strong></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                 <a href="{% url 'blog' %}">新闻日志</a>
                                            </li>
                                            <li>
                                                 <a href="{% url 'team' %}">团队成员</a>
                                            </li>
                                            <li>
                                                 <a href="{% url 'joinus' %}">加入我们</a>
                                            </li>
                                            <li class="divider">
                                            </li>
                                            <li>
                                                 <a href="{% url 'contact' %}">联系我们</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                                <form class="navbar-form navbar-left" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" />
                                    </div> <button type="submit" class="btn btn-default">搜索</button>
                                </form>
                                <ul class="nav navbar-nav navbar-right">
                                    <li>
                                         <a href="#">F&Q</a>
                                    </li>
                                    {% if user.is_authenticated %}
                                    <li>
                                         <a href="{% url 'home' %}">回到主页</a>
                                    </li>
                                    {% endif %}
                                    <li class="dropdown">
                                         <a href="#" id="rightest" class="dropdown-toggle" data-toggle="dropdown">用户<strong class="caret"></strong>&nbsp</a>
                                        <ul class="dropdown-menu">
                                            {% if user.is_authenticated %}
                                            <li>
                                                <a href="{% url 'logout' %}">注销</a>
                                            </li>
                                            {% else %}
                                            <li>
                                                <a href="{% url 'login' %}">登录</a>
                                            </li>
                                            <li>
                                                 <a href="{% url 'signup' %}">注册</a>
                                            </li>
                                            {% endif %}
                                            <li class="divider">
                                            </li>
                                            <li>
                                                 <a href="#">首页</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>

                        </nav>
                    </div>
                </div>
            </div>

        </header>
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

ailingx/templates/blog.html
{% extends 'base.html' %}

{% block title %}日志{% endblock %}

{% block content %}
    <div id="particles" class="test">
      <div id="intro">
        <h1 id="indexh1">日志</h1>
      </div>
    </div>
{% endblock %}

ailingx/templates/contact.html
{% extends 'base.html' %}

{% block title %}联系我们{% endblock %}

{% block content %}
    <div id="particles" class="test">
      <div id="intro">
        <h1 id="indexh1">欢迎联系我们</h1>
      </div>
    </div>
{% endblock %}

ailingx/templates/feature.html
{% extends 'base.html' %}

{% block title %}产品特性{% endblock %}

{% block content %}
    <div id="particles" class="test">
      <div id="intro">
        <h1 id="indexh1">产品介绍</h1>
      </div>
    </div>
{% endblock %}

ailingx/templates/home.html
{% extends 'base.html' %}

{% block title %}用户面板{% endblock %}

{% block content %}
    <br>
    <br>
  <h2>Welcome, {{ curuser.get_full_name }}!</h2>
  <p>Your location: {{ curuser.profile.location }}</p>
    {% for cell in cells %}
        <h3>{{ cell }}|{{ cell.block }}|{{ cell.block.area }}</h3>
    {% endfor %}
{% endblock %}

ailingx/templates/index.html
{% extends 'base.html' %}

{% block title %}零晓科技{% endblock %}

{% block content %}
    <div id="particles" class="test">
        <div id="intro">
            <h1 id="indexh1">欢迎来到零晓科技</h1>
            <h2 id="indexh2">农林业+AI+国际化</h2>
            <a id="indexdemo" href="{% url 'demo:demogis' %}" class="btn">DEMO</a>
            <a id="indexdemo" href="{% url 'tenihe:tenihegis' %}" class="btn">特泥河</a>
        </div>
    </div>
{% endblock %}

ailingx/templates/joinus.html
{% extends 'base.html' %}

{% block title %}加入我们{% endblock %}

{% block content %}
    <div id="particles" class="test">
      <div id="intro">
        <h1 id="indexh1">加入我们</h1>
      </div>
    </div>
{% endblock %}

ailingx/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Log in to Ailingx</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

ailingx/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up for Ailingx</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

ailingx/templates/team.html
{% extends 'base.html' %}

{% block title %}团队成员{% endblock %}

{% block content %}
    <div id="particles" class="test">
      <div id="intro">
        <h1 id="indexh1">马晓航「Founder&CEO」</h1>
        <h1 id="indexh1">宋浩南「Co-Founder&COO」</h1>
      </div>
    </div>
{% endblock %}

ailingx/templates/usecase.html
{% extends 'base.html' %}

{% block title %}案例{% endblock %}

{% block content %}
    <div id="particles" class="test">
      <div id="intro">
        {%  for area in areas %}
        <h1 id="indexh1">{{ area }}</h1>
            {% for block in area.block_set.all %}
                <h2 id="indexh2">{{ block }}</h2>
                {% for cell in block.cell_set.all %}
                    <h3>{{ cell }}</h3>
                {% endfor %}
            {% endfor %}
        {%  endfor %}
      </div>
    </div>
{% endblock %}