ailingx/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from ailingx.core import views as core_views
from demo import views,urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),

    url(r'^home/$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),

    url(r'^usecase/$', core_views.usecase, name='usecase'),
    url(r'^feature/$', core_views.feature, name='feature'),
    url(r'^blog/$', core_views.blog, name='blog'),
    url(r'^team/$', core_views.team, name='team'),
    url(r'^joinus/$', core_views.joinus, name='joinus'),
    url(r'^contact/$', core_views.contact, name='contact'),

    url(r'^admin/', admin.site.urls),

    url(r'^demo/', include('demo.urls', namespace='demo')),
    url(r'^tenihe/', include('tenihe.urls', namespace='tenihe')),

] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

demo/urls.py
from django.conf.urls import url
from demo import views

urlpatterns = [
    url(r'^demogis/$', views.demogis, name='demogis'),
    url(r'^demomap/(\d+)$', views.demomap, name='demomap'),
]

tenihe/urls.py
from django.conf.urls import url
from tenihe import views

urlpatterns = [
    url(r'^tenihegis/$', views.tenihegis, name='tenihegis'),
    url(r'^tenihemap/(\d+)$', views.tenihemap, name='tenihemap'),
]

tenihe/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tenihe/views.py
#-*- coding: UTF-8 -*-
from django.shortcuts import render
import json
import random
import math
# Create your views here.

def tenihegis(request):
    return render(request, 'tenihegis.html')


class IllTree:

    def __init__(self, index, lng, lat, area, count):
        self.index = index
        self.lng = lng
        self.lat = lat
        self.area = area
        self.count = count


class CellImg:

    def __init__(self, index, name, center_pt_lng, center_pt_lat, zoom_level, img_n, img_s, img_w, img_e, img_url_nc, img_url_ndvi, img_url_th):
        self.index = index
        self.name = name
        self.center_pt_lng = center_pt_lng
        self.center_pt_lat = center_pt_lat
        self.zoom_level = zoom_level
        self.img_n = img_n
        self.img_s = img_s
        self.img_w = img_w
        self.img_e = img_e
        self.img_url_nc = img_url_nc
        self.img_url_ndvi = img_url_ndvi
        self.img_url_th = img_url_th


def tenihemap(request, param1):

    abc_id = param1
    abc_name = abc_id_to_abc_name(abc_id)
    (centerPlng, centerPlat, zoom) = abc_id_to_abc_centerP(abc_id)
    nswe = abc_id_to_abc_imgloc(abc_id)
    (NCurl, NDVIurl, THurl) = abc_id_to_abc_imgurl(abc_id)
    (f_date, f_weather, f_temperature, f_winddir, f_windpower, f_humidity ) = abc_id_to_abc_weather(abc_id)

    illtreecount = random.randint(15, 30)
    illtrees = []
    for i in range(0, illtreecount):
        num = random.randint(5, 100)
        aindex = i
        lng = round(random.uniform(float(nswe[1]), float(nswe[0])), 6)
        lat = round(random.uniform(float(nswe[2]), float(nswe[3])), 6)
        area = num*random.randint(1, 5)
        count = num
        a_illtree = IllTree(aindex, lng, lat, area, count)
        illtrees.append(a_illtree)

    return render(request, 'tenihemap.html', {
        'abc_id': abc_id,
        'abc_name': abc_name,
        'centerPlng': json.dumps(centerPlng),
        'centerPlat': json.dumps(centerPlat),
        'zoom': json.dumps(zoom),
        'img_nswe': json.dumps(nswe),
        'NCurl': json.dumps(NCurl),
        'NDVIurl': json.dumps(NDVIurl),
        'THurl': json.dumps(THurl),
        'illtrees': illtrees,
        'f_date': f_date,
        'f_weather': f_weather,
        'f_temperature': f_temperature,
        'f_winddir': f_winddir,
        'f_windpower': f_windpower,
        'f_humidity': f_humidity,
    })



def getcell(argument):
    switcher = {
        '0108001': CellImg(108001,"特泥河农场八队001地块",120.362,49.52439,15,49.52809,49.51962,120.3554,120.36856,'static/img/Dateimg/1.png','static/img/Dateimg/2.png','static/img/Dateimg/3.png'),
    }
    return switcher.get(argument, None)


def abc_id_to_abc_name(argument):
    switcher = {
        '010801': "特泥河农场八队2017-08-16架次",
        '010802': "特泥河农场八队2017-08-30架次",
        '010804': "特泥河农场八队2017-10-18架次",
        '010800101': "特泥河农场八队001地块2017-08-16架次",
        '010800201': "特泥河农场八队002地块2017-08-16架次",
        '010800102': "特泥河农场八队001地块2017-08-30架次",
        '010800202': "特泥河农场八队002地块2017-08-30架次",
        '010800104': "特泥河农场八队001地块2017-10-18架次",
        '010800204': "特泥河农场八队002地块2017-10-18架次",
    }
    return switcher.get(argument, "nothing")


def abc_id_to_abc_centerP(argument):
    switcherlng = {
        '010801': "120.35625",
        '010802': "120.35625",
        '010804': "120.35625",
        '010800101': "120.36365",
        '010800201': "120.34881",
        '010800102': "120.36365",
        '010800202': "120.34881",
        '010800104': "120.36365",
        '010800204': "120.34881",
    }
    switcherlat = {
        '010801': "49.5297",
        '010802': "49.5297",
        '010804': "49.5297",
        '010800101': "49.52156",
        '010800201': "49.52691",
        '010800102': "49.52156",
        '010800202': "49.52691",
        '010800104': "49.52156",
        '010800204': "49.52691",
    }
    switcherzoom = {
        '010801': "15",
        '010802': "15",
        '010804': "15",
        '010800101': "18",
        '010800201': "18",
        '010800102': "18",
        '010800202': "18",
        '010800104': "18",
        '010800204': "18",
    }
    return switcherlng.get(argument, "120"), \
           switcherlat.get(argument, "49"), \
           switcherzoom.get(argument, "15")


def abc_id_to_abc_imgloc(argument):
    switchernorth = {
        '010801': "49.54289",
        '010802': "49.54289",
        '010804': "49.54289",
        '010800101': "49.52325",
        '010800201': "49.52935",
        '010800102': "49.52325",
        '010800202': "49.52935",
        '010800104': "49.52325",
        '010800204': "49.52935",
    }
    switchersouth = {
        '010801': "49.51583",
        '010802': "49.51583",
        '010804': "49.51583",
        '010800101': "49.520",
        '010800201': "49.5243",
        '010800102': "49.520",
        '010800202': "49.5243",
        '010800104': "49.520",
        '010800204': "49.5243",
    }
    switcherwest = {
        '010801': "120.33527",
        '010802': "120.33527",
        '010804': "120.33527",
        '010800101': "120.35877",
        '010800201': "120.34283",
        '010800102': "120.35877",
        '010800202': "120.34283",
        '010800104': "120.35877",
        '010800204': "120.34283",
    }
    switchereast = {
        '010801': "120.37551",
        '010802': "120.37551",
        '010804': "120.37551",
        '010800101': "120.36831",
        '010800201': "120.35726",
        '010800102': "120.36831",
        '010800202': "120.35726",
        '010800104': "120.36831",
        '010800204': "120.35726",
    }
    return switchernorth.get(argument, "49"),\
           switchersouth.get(argument, "49"),\
           switcherwest.get(argument, "120"),\
           switchereast.get(argument, "120")


def abc_id_to_abc_imgurl(argument):
    switchernc = {
        '010801': "/static/img/Blockimg/0108_01_nc.png",
        '010802': "/static/img/Blockimg/0108_02_nc.png",
        '010804': "/static/img/Blockimg/0108_04_nc.png",
        '010800101': "/static/img/Dateimg/0108001_01_nc.png",
        '010800201': "/static/img/Dateimg/0108002_01_nc.png",
        '010800102': "/static/img/Dateimg/0108001_02_nc.png",
        '010800202': "/static/img/Dateimg/0108002_02_nc.png",
        '010800104': "/static/img/Dateimg/0108001_04_nc.png",
        '010800204': "/static/img/Dateimg/0108002_04_nc.png",
    }
    switcherndvi = {
        '010801': "/static/img/Blockimg/0108_01_ndvi.png",
        '010802': "/static/img/Blockimg/0108_02_ndvi.png",
        '010804': "/static/img/Blockimg/0108_04_ndvi.png",
        '010800101': "/static/img/Dateimg/0108001_01_ndvi.png",
        '010800201': "/static/img/Dateimg/0108002_01_ndvi.png",
        '010800102': "/static/img/Dateimg/0108001_02_ndvi.png",
        '010800202': "/static/img/Dateimg/0108002_02_ndvi.png",
        '010800104': "/static/img/Dateimg/0108001_04_ndvi.png",
        '010800204': "/static/img/Dateimg/0108002_04_ndvi.png",
    }
    switcherthermal = {
        '010801': "/static/img/Blockimg/0108_01_thermal.png",
        '010802': "/static/img/Blockimg/0108_02_thermal.png",
        '010804': "/static/img/Blockimg/0108_04_thermal.png",
        '010800101': "/static/img/Dateimg/0108001_01_thermal.png",
        '010800201': "/static/img/Dateimg/0108002_01_thermal.png",
        '010800102': "/static/img/Dateimg/0108001_02_thermal.png",
        '010800202': "/static/img/Dateimg/0108002_02_thermal.png",
        '010800104': "/static/img/Dateimg/0108001_04_thermal.png",
        '010800204': "/static/img/Dateimg/0108002_04_thermal.png",
    }
    return switchernc.get(argument, "/static/img/default.png"),\
           switcherndvi.get(argument, "/static/img/default.png"),\
           switcherthermal.get(argument, "/static/img/default.png"),

def abc_id_to_abc_weather(argument):
    switcherdate = {
        '010800101': "2017-08-16 15:00:00",
        '010800201': "2017-08-16 15:00:00",
        '010800102': "2017-08-30 11:00:00",
        '010800202': "2017-08-30 11:00:00",
        '010800104': "2017-10-18 11:30:00",
        '010800204': "2017-10-18 11:30:00",
    }
    switcherweather = {
        '010800101': "多云",
        '010800201': "多云",
        '010800102': "晴",
        '010800202': "晴",
        '010800104': "晴",
        '010800204': "晴",
    }
    switchertemperature = {
        '010800101': "16~29℃",
        '010800201': "16~29℃",
        '010800102': "5~16℃",
        '010800202': "5~16℃",
        '010800104': "-5~6℃",
        '010800204': "-5~6℃",
    }
    switcherwinddir = {
        '010800101': "西风",
        '010800201': "西风",
        '010800102': "北风",
        '010800202': "北风",
        '010800104': "西风",
        '010800204': "西风",
    }
    switcherwindpower = {
        '010800101': "2级",
        '010800201': "2级",
        '010800102': "3级",
        '010800202': "3级",
        '010800104': "3级",
        '010800204': "3级",
    }
    switcherhumidity = {
        '010800101': "35",
        '010800201': "35",
        '010800102': "50",
        '010800202': "50",
        '010800104': "30",
        '010800204': "30",
    }
    return switcherdate.get(argument, ""),\
           switcherweather.get(argument, "未记录"),\
           switchertemperature.get(argument, "--"),\
           switcherwinddir.get(argument, "未记录"),\
           switcherwindpower.get(argument, "--"),\
           switcherhumidity.get(argument, "--")

tenihe/templates/Bdate.html
<div class="panel-group" id="b-accordion">
    <div class="card-date panel">
        <div>
            <h5 class="date_title" id="C_tnh_08_04" data-toggle="collapse" data-parent="#b-accordion" href="#b-date4">2017-10-18</h5>
        </div>
        <div id="b-date4" class="collapse in">
            <div id="C_tnh_08_04_info">
                异常点数量为1个，正常。
            </div>
            <div id="C_tnh_08_04_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010801' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108_04_s.png" ></a>
            </div>
        </div>
    </div>
    <div class="card-date panel">
        <div>
             <h5 class="date_title" id="C_tnh_08_02" data-toggle="collapse" data-parent="#b-accordion" href="#b-date2">2017-08-30</h5>
        </div>
        <div id="b-date2" class="collapse">
            <div id="C_tnh_08_02_info">
                异常点数量为1个，正常。
            </div>
            <div id="C_tnh_08_02_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010802' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108_02_s.png" ></a>
            </div>
        </div>
    </div>
    <div class="card-date panel">
        <div>
             <h5 class="date_title" id="C_tnh_08_01" data-toggle="collapse" data-parent="#b-accordion" href="#b-date1">2017-08-16</h5>
        </div>
        <div id="b-date1" class="collapse">
            <div id="C_tnh_08_01_info">
                异常点数量为1个，正常。
            </div>
            <div id="C_tnh_08_01_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010804' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108_01_s.png" ></a>
            </div>
        </div>
    </div>
</div>

tenihe/templates/C01date.html
<div class="panel-group" id="c01-accordion">
    <div class="card-date panel">
        <div>
            <h5 class="date_title" id="D_tnh_08_001_04" data-toggle="collapse" data-parent="#c01-accordion" href="#c01-date4">2017-10-18</h5>
        </div>
        <div id="c01-date4" class="collapse in">
            <div id="D_tnh_08_001_04_info">
                异常点数量为1个，正常。
            </div>
            <div id="D_tnh_08_001_04_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010800104' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108001_04_s.png" ></a>
            </div>
        </div>
    </div>
    <div class="card-date panel">
        <div>
             <h5 class="date_title" id="D_tnh_08_001_02" data-toggle="collapse" data-parent="#c01-accordion" href="#c01-date2">2017-08-30</h5>
        </div>
        <div id="c01-date2" class="collapse">
            <div id="D_tnh_08_001_02_info">
                异常点数量为1个，正常。
            </div>
            <div id="D_tnh_08_001_02_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010800102' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108001_02_s.png" ></a>
            </div>
        </div>
    </div>
    <div class="card-date panel">
        <div>
             <h5 class="date_title" id="D_tnh_08_001_01" data-toggle="collapse" data-parent="#c01-accordion" href="#c01-date1">2017-08-16</h5>
        </div>
        <div id="c01-date1" class="collapse">
            <div id="D_tnh_08_001_01_info">
                异常点数量为1个，正常。
            </div>
            <div id="D_tnh_08_001_01_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010800101' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108001_01_s.png" ></a>
            </div>
        </div>
    </div>
</div>

tenihe/templates/C02date.html
<div class="panel-group" id="c02-accordion">
    <div class="card-date panel">
        <div>
            <h5 class="date_title" id="D_tnh_08_002_04" data-toggle="collapse" data-parent="#c02-accordion" href="#c02-date4">2017-10-17</h5>
        </div>
        <div id="c02-date4" class="collapse in">
            <div id="D_tnh_08_002_04_info">
                异常点数量为1个，正常。
            </div>
            <div id="D_tnh_08_002_04_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010800204' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108002_04_s.png" ></a>
            </div>
        </div>
    </div>
    <div class="card-date panel">
        <div>
             <h5 class="date_title" id="D_tnh_08_002_02" data-toggle="collapse" data-parent="#c02-accordion" href="#c02-date2">2017-08-30</h5>
        </div>
        <div id="c02-date2" class="collapse">
            <div id="D_tnh_08_002_02_info">
                异常点数量为1个，正常。
            </div>
            <div id="D_tnh_08_002_02_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010800202' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108002_02_s.png" ></a>
            </div>
        </div>
    </div>
    <div class="card-date panel">
        <div>
             <h5 class="date_title" id="D_tnh_08_002_01" data-toggle="collapse" data-parent="#c02-accordion" href="#c02-date1">2017-08-16</h5>
        </div>
        <div id="c02-date1" class="collapse">
            <div id="D_tnh_08_001_02_info">
                异常点数量为1个，正常。
            </div>
            <div id="D_tnh_08_001_02_img" class="date_img_div">
                <a href="{% url 'tenihe:tenihemap' '010800201' %}"  target="_blank" data-toggle="tooltip" title="点击图标显示详细数据">
                <img class="date_img" src="/static/img/Thumbnail/0108002_01_s.png" ></a>
            </div>
        </div>
    </div>
</div>

tenihe/templates/DataDiv.html
<div id="dataDiv">
    <div id="dataBar" >
        {% include 'SysNavDiv.html' %}
        {% include 'LayerDiv.html' %}
        <div id="weather_panel" style="display: block">
            {%  include 'Weather.html' %}
        </div>
        <div id="userdata_panel" style="display: none">
            {% include 'Userdata.html' %}
        </div>


    </div>
    <div id="dataToggle" class="ToggleLogoleftArrow">

    </div>
</div>

tenihe/templates/IntroDiv.html
<div class="intropanel">
    <div id="sys_panel">
        <div class="card-lightgreen">
            <h3>呼伦贝尔农垦</h3>
            <p>
                呼伦贝尔农垦集团是一个最有条件、最有基础、最有特色、最有潜力、优势明显、后劲十足的大型国有农垦企业：
            </p>
            <ul>
                <li>一、资源丰富，有施业区面积3万平方公里，分布在呼伦贝尔9个旗市区境内，拥有600万亩耕地、1000万亩草场、40万亩林地、13万亩水面；</li>
                <li>二、规模大，辖24个县团级现代化农牧场和27个企事业单位，总人口17万，其中各类从业人员7.4万；</li>
                <li>三、组织化程度高，企业实行准军事化管理模式，是全国仅有的规模化、集约化垦区之一；</li>
                <li>四、农牧业机械装备能力强，采用世界最先进的大型农机设备为主，总动力74.2万千瓦，田间农业综合机械化水平达95%；</li>
                <li>五、科技实力雄厚，有各类专业技术人员4263人，农业科技贡献率71.38%，处于全国领先水平；</li>
                <li>六、区位优越，生态良好，适宜打造绿色有机农产品基地。</li>
            </ul>
        </div>
        <div class="card-orange">
            <h4>
                 单击列表跳转至该地区视野。
            </h4>
            <ul>
                <li>单击第一级列表显示农场</li>
                <li>单击第二级列表显示生产队</li>
                <li>单击第三级列表显示地块</li>
            </ul>
        </div>
        <div class="card-darkgreen">
            <ul>
                <li><span class="glyphicon glyphicon-map-marker"></span>：无数据，单击跳转地区信息图</li>
                <li><span class="glyphicon glyphicon-fullscreen"></span>：有数据，单击跳转地区高清图</li>

            </ul>
        </div>
    </div>


    <div id="Area_panel" style="display:none">
        <div class="card-midgreen">
            <h4>头条新闻</h4>
            <strong>2017-11-11</strong>
            <p id="area_new">
                今年特泥河农场粮食产量比去年增长20%！
            </p>
        </div>
        <div class="card-darkgreen">
            <h4>特泥河农牧场</h4>
            <strong>呼伦贝尔农垦</strong>
            <p id="coordinate"></p>
            <p id="area_intro">
                特泥河牧场地处陈巴尔虎旗东南部，在东经119°45'~120°55'、北纬49°13'~49°50'之间，平均海拔650米。
                地处呼伦贝尔盟陈巴尔虎旗东南部。场区东西长76公里。南：化宽66公里，总面积为1900平方公里，约占全旗总面积的8.97%。
                其中草原120万亩，可垦耕地67万亩，林地30万亩，水面5万亩，村屯道路6万亩，低洼沼泽地J0万亩，山岭砂地17万亩。
            </p>
        </div>
        <div class="card-lightgreen">
            <p>
                草原面积126万亩，耕地面积38万亩，人工林地面积1.9万亩。
            </p>
        </div>
        <div class="card-orange">
            <p>
                全场38万亩耕地全部实施免耕播种，5.48万耕地实现了抗旱节水灌溉；
                建成了以农业科技研发和新品种繁育推广为核心的科技试验示范园区一处，建成现代化农业样板队两个（二队、四队）。
                在测土配方施肥技术、水肥一体化技术、免耕滴灌铺管技术等方面积极积累了较好的经验。
                几年来，农机具更新度系数达到82%，全场拥有国内外先进农机具1207台（件），
                机械总动力达2.89万千瓦，有水泥晒场29万平方米，晒棚4万平方米。
            </p>
        </div>
    </div>

    <div id="Block_panel" style="display:none">
        <div class="card-darkgreen" >
            <h4 id="block_id">XX生产队</h4>
            <strong>特泥河农牧场</strong>
            <p id="block_intro">
                XX生产队介绍
            </p>
            <p id="block_data">
                XX生产队数据
            </p>
            <p  id="block_info">
                XX生产队信息
            </p>
        </div>
        <div class="card-midgreen">
            <h4>生产队新闻</h4>
            <strong>2017-11-11</strong>
            <p id="block_new">
                近日生产队大丰收
            </p>

        </div>
        {%  include 'Bdate.html' %}
    </div>
    <div id="Cell_panel" style="display:none">
        <div class="card-darkgreen">
            <h4><strong id="cell_id">XX生产队010x00x地块</strong> <small  id="cell_data" style="color: #f1f2f2"></small></h4>
            <strong id="cell_block"></strong>
            <p id="cell_intro">
                XX生产队010x00x地块情况
            </p>
            <p id="cell_newest">
                XX生产队010x00x地块情况
            </p>
        </div>

        <div class="manage_func_card card-midgreen">
            <div id="func_water" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-tint" ></span>水分值</div>
            <div id="func_organic" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-certificate" ></span>肥力值</div>
            <div id="func_health" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-plus-sign" ></span>健康度</div>
            <div id="func_grow" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-tree-deciduous" ></span>成熟度</div>
            <div id="func_emerge" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-leaf" ></span>出苗率</div>
            <div id="func_ill_crop" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-warning-sign" ></span>异常点</div>
            <div id="func_patrol" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-camera" ></span>巡田处</div>
            <div id="func_insurance" class="manage_func_btn"><span class="optionToolIcon glyphicon glyphicon-exclamation-sign" ></span>报险处</div>

        </div>
        <div>
            <div id="C01date" style="display: none">
                {% include 'C01date.html' %}
            </div>
            <div id="C02date" style="display: none">
                {% include 'C02date.html' %}
            </div>
        </div>
    </div>


</div>

tenihe/templates/LIstDiv.html
<div id="listDiv">
    <div id="listBar">

        {% include 'ABClistDiv.html' %}

    </div>
    <div id="listToggle" class="ToggleLogorightArrow"></div>

</div>

tenihe/templates/SysNavDiv.html
<div class="sys_func_card card-orange">
    <div id="Tool0" class="optionToolBlock">
        <a href="{% url 'index' %}">
            <span data-toggle="tooltip" title="返回首页" class="optionToolIcon glyphicon glyphicon-home"></span></a>
    </div>
    <div id="Tool1" class="optionToolBlock">
        <span data-toggle="tooltip" title="搜索" class="optionToolIcon glyphicon glyphicon-search" style="cursor: pointer"></span>

    </div>
    <div id="Tool2" class="optionToolBlock">
        <span data-toggle="tooltip" title="帮助" class="optionToolIcon glyphicon glyphicon-question-sign" style="cursor: pointer"></span>
    </div>
    <div id="Tool4" class="optionToolBlock">
        <span data-toggle="tooltip" title="去除高程" id="toGround" class="optionToolIcon glyphicon glyphicon-eject" style="cursor: pointer"></span>
    </div>
</div>

tenihe/templates/Userdata.html
<div class="card-lightgreen">
    <h4>用户标记数据</h4>
    <table id="tool2data"  width="100%">
    </table>
</div>
<div class="card-lightgreen">
    <h4>用户长度数据</h4>
    <table id="tool3data"  width="100%">
    </table>
</div>
<div class="card-lightgreen">
    <h4>用户面积数据</h4>
    <table id="tool4data" width="100%">

    </table>
</div>

tenihe/templates/Weather.html
<div class="card-lightgreen">
    <h4>飞行任务天气记录</h4>
    <table id="flight_weather"  width="100%">
        <tr class="table_date"><td>作业时间</td><td>{{ f_date }}</td></tr>
        <tr><td>天气</td><td>{{ f_weather }}</td></tr>
        <tr><td>温度</td><td>{{ f_temperature }}</td></tr>
        <tr><td>风向</td><td>{{ f_winddir }}</td></tr>
        <tr><td>风力</td><td>{{ f_windpower }}</td></tr>
        <tr><td>湿度</td><td>{{ f_humidity }}</td></tr>
    </table>
</div>
<div class="card-lightgreen">
    <h4>实时天气</h4>
    <table id="realtime_wrather"  width="100%">
        <tr class="table_date"><td>发布时间</td><td></td></tr>
        <tr><td>天气</td><td></td></tr>
        <tr><td>温度</td><td></td></tr>
        <tr><td>风向</td><td></td></tr>
        <tr><td>风力</td><td></td></tr>
        <tr><td>湿度</td><td></td></tr>
    </table>
</div>
<div class="card-lightgreen">
    <h4>天气预报</h4>
    <table id="forcast_weather" width="100%">
        <tr><td>发布时间</td><td></td></tr>
        <tr class="table_date"><td>日期</td><td></td></tr>
        <tr><td>天气</td><td></td></tr>
        <tr><td>温度</td><td></td></tr>
        <tr><td>风向</td><td></td></tr>
        <tr><td>风力</td><td></td></tr>
        <tr class="table_date"><td>日期</td><td></td></tr>
        <tr><td>天气</td><td></td></tr>
        <tr><td>温度</td><td></td></tr>
        <tr><td>风向</td><td></td></tr>
        <tr><td>风力</td><td></td></tr>
        <tr class="table_date"><td>日期</td><td></td></tr>
        <tr><td>天气</td><td></td></tr>
        <tr><td>温度</td><td></td></tr>
        <tr><td>风向</td><td></td></tr>
        <tr><td>风力</td><td></td></tr>
        <tr class="table_date"><td>日期</td><td></td></tr>
        <tr><td>天气</td><td></td></tr>
        <tr><td>温度</td><td></td></tr>
        <tr><td>风向</td><td></td></tr>
        <tr><td>风力</td><td></td></tr>
    </table>
</div>